#ifndef SETTINGSDEFENITIONS_H
#define SETTINGSDEFENITIONS_H

#define LIST_ENTRY_STATE 0
#define OFF_ON_ENTRY_STATE 1
#define HEADER 2

//#define COMMON_SETTINGS "Общие"
//#define SYSTEM_SETTINGS "Системные"

#endif // SETTINGSDEFENITIONS_H
